### ISSUE TITLE
Nvidia GPU not detected

### ISSUE THREAD

**Issue by denkyem** [imagegenius/docker-immich#505]
I'm running Immich on Unraid

I use a Nvidia Quadro P2000 to ML and transcode.
It was working fine until last update to 1.130.1

Now, when I start any action that should use GPU, it falls back to CPU and logs that OpenVINO device not found.

<img width="668" alt="Image" src="https://github.com/user-attachments/assets/d407b1f6-5d6d-4cd6-bf45-319b677b9c54" />

<img width="423" alt="Image" src="https://github.com/user-attachments/assets/3709c282-eece-4ec8-a8cb-cf54396448de" />

<img width="450" alt="Image" src="https://github.com/user-attachments/assets/0a97c728-1158-4664-a6f7-9fc7727d2db0" />

<img width="734" alt="Image" src="https://github.com/user-attachments/assets/e61ca7e4-d4d0-48fd-848c-f066dce8c33c" />

Any help?

Thanks

**Comment by NAdoTEg** [comment]
I'm getting this problem as well. Switched to OpenVINO instead of CUDA even though nvidia runtime is specified and cuda version of immich is being used

**Comment by martabal** [comment]
Unfortunately, I no longer have a Nvidia GPU to fix/debug this issue. I opened #506 to try to fix it. I would appreciate it if someone could try that PR.

**Comment by martabal** [comment]
You can try the PR with this image: ghcr.io/imagegenius/igpipepr-immich:1.130.2-pr-506

**Comment by Yan-nian** [comment]
yes also encounter

**Comment by denkyem** [comment]
> ghcr.io/imagegenius/igpipepr-immich:1.130.2-pr-506

I'll give it a try and report back to you later

**Comment by denkyem** [comment]
> You can try the PR with this image: ghcr.io/imagegenius/igpipepr-immich:1.130.2-pr-506

It seems to be working fine

<img width="676" alt="Image" src="https://github.com/user-attachments/assets/b6c0f587-c0d6-446f-beab-c1d039ad24cc" />

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/52a1c4f1-ee34-49f3-b89d-8eaaee27feb6" />

**Comment by zenaufa** [comment]
Thank you for the fix, it works for me 
![Image](https://github.com/user-attachments/assets/177826b2-fef2-479e-b7e2-cdcebc0f9c4b)

**Comment by zenaufa** [comment]
Thank you for the fix, it works for me
![Image](https://github.com/user-attachments/assets/97896276-7311-4d14-b85d-2b3ca46ba99a)
